name: Shopware Plugin Verification

on:
  pull_request:
    branches: [main, develop]
  push:
    branches:
      - '**'
    tags:
      - "v*.*.*"

jobs:
  verify-plugin:
    name: Verify Shopware Plugin
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version-selection: ['lowest', 'highest']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Shopware Extension Verifier
        id: verifier
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}

      - name: ❌ Extension Verifier Failed – Errors were found
        if: failure() && steps.verifier.outcome == 'failure'
        env:
          VERSION_SELECTION: ${{ matrix.version-selection }}
        run: |
          echo "❌ Shopware Extension Verifier detected issues. Please review and fix them."
          echo "### ❌ Shopware Extension Verifier Failed (${VERSION_SELECTION})" >> $GITHUB_STEP_SUMMARY

      - name: ✅ Extension Verifier Passed – No errors found
        if: success() && steps.verifier.outcome == 'success'
        env:
          VERSION_SELECTION: ${{ matrix.version-selection }}
        run: |
          echo "✅ Shopware Extension Verifier ran successfully. No issues found!"
          echo "### ✅ Shopware Extension Verifier Passed (${VERSION_SELECTION})" >> $GITHUB_STEP_SUMMARY
